before_script:
  - apt-get update
  - apt-get install maven openjdk-8-jre -y

maven:
  stage: test
  script:
    - test/run.sh
  
before_script:
  - apt-get update
  - apt-get install maven openjdk-8-jre -y
  
mvn:
  stage: deploy
  before_script:
    - mvn package
  script:
    - java -jar complete/gs-maven-0.1.0.jar